
<!-- this issue template is used by https://github.com/apps/first-timers -->

# 🆕🐥☝ First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

[About First Timers Only](http://www.firsttimersonly.com/).

## 🤔 What you will need to know
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## :clipboard: Step by Step
- [ ] 🙋 **Claim this issue**: Comment below to let other people know that you're working on this issue.
- [ ] 🔀 **Fork our repository**:  You'll need [to fork this repository](https://help.github.com/articles/fork-a-repo) in order to propose a change.
- [ ] 📝 **Update** the file [$FILENAME in the `your-username-here/$REPO` repository]($BRANCH_URL) and edit the line as shown below.

```diff
$DIFF
```

- [ ] 🔀 **Start a Pull Request**. You can [create a pull request in Github](https://help.github.com/articles/creating-a-pull-request/). Mention `closes nickcolley/jest-axe#THIS_ISSUE_NUMBER` in the description.
- [ ] 🏁 **Done** :+1: We'll review the Pull Request and let you know if any changes are needed.

## 🤔❓ Questions

Comment on this issue or [message Nick on Twitter](https://twitter.com/nickcolley/).
